<a href="https://colab.research.google.com/github/brownt47/Deep_Learning/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [186]:
import pandas as pd
import numpy as np
#import matplotlib.plot as plt
import tensorflow as tf

In [187]:
tf.__version__

'2.6.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [188]:
data = pd.read_csv("Churn_Modelling.csv")

In [189]:
len(data)

10000

In [190]:
print(data.Geography)

0        France
1         Spain
2        France
3        France
4         Spain
         ...   
9995     France
9996     France
9997     France
9998    Germany
9999     France
Name: Geography, Length: 10000, dtype: object


In [191]:
X = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values

In [192]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [193]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [194]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [195]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [196]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [197]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [198]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [199]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [200]:
ann = tf.keras.Sequential()

### Adding the input layer and the first hidden layer

In [201]:
ann.add(tf.keras.layers.Dense(units = 8, activation = 'relu'))

### Adding the second hidden layer

In [202]:
ann.add(tf.keras.layers.Dense(units = 8, activation = 'relu'))

### Adding the third hidden layer

In [203]:
ann.add(tf.keras.layers.Dense(units = 8, activation = 'relu'))

### Adding the output layer

In [204]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [205]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

### Training the ANN on the Training set

In [242]:
ann.fit(X_train, y_train, batch_size= 64, epochs= 100)

Epoch 1/100
125/125 [==============================] - 0s 2ms/step - loss: 0.3393 - accuracy: 0.8590
Epoch 2/100
125/125 [==============================] - 0s 2ms/step - loss: 0.3383 - accuracy: 0.8614
Epoch 3/100
125/125 [==============================] - 0s 2ms/step - loss: 0.3377 - accuracy: 0.8600
Epoch 4/100
125/125 [==============================] - 0s 2ms/step - loss: 0.3375 - accuracy: 0.8599
Epoch 5/100
125/125 [==============================] - 0s 1ms/step - loss: 0.3371 - accuracy: 0.8615
Epoch 6/100
125/125 [==============================] - 0s 2ms/step - loss: 0.3363 - accuracy: 0.8621
Epoch 7/100
125/125 [==============================] - 0s 2ms/step - loss: 0.3361 - accuracy: 0.8600
Epoch 8/100
125/125 [==============================] - 0s 1ms/step - loss: 0.3361 - accuracy: 0.8610
Epoch 9/100
125/125 [==============================] - 0s 2ms/step - loss: 0.3355 - accuracy: 0.8612
Epoch 10/100
125/125 [==============================] - 0s 1ms/step - loss: 0.3354 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [243]:
customer = [600, 'France','Male', 40, 3, 60000, 2, 1, 1, 50000]

#### Encode the gender

In [244]:
customer[2]= le.transform([customer[2]])[0]

##### Encode the Geography

In [245]:
customer = ct.transform([customer])

##### Scaling the customer features

In [246]:
customer = sc.transform(customer)

#### Predict if customer will churn and leave the bank

In [247]:
if (ann.predict(customer)[0][0] > 0.5):
  print('Customer will leave')
else:
  print('Customer will not leave')


Customer will not leave


**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [248]:
y_pred = ann.predict(X_test) > 0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [249]:
from sklearn.metrics import *
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1549   46]
 [ 225  180]]


In [250]:
accuracy_score(y_test, y_pred)

0.8645

In [251]:
recall_score(y_test, y_pred)

0.4444444444444444

In [252]:
f1_score(y_test, y_pred)

0.5705229793977813

In [253]:
precision_score(y_test, y_pred)

0.7964601769911505